### ISSUE TITLE
五個銳音歌三字

### ISSUE THREAD

**Issue by LEOYoon-Tsaw** [nk2028/rime-dict-source#1]
這五個字「脞㛗侳𩛠𡎬」按韻典是戈（歌）韻三等字，但char.tsv中記爲了一等

**Comment by syimyuzya** [comment]
> 按韻典

韻典的處理是有問題的。

韻典資料是按照反切下字的「三等」硬切的，但實際上切韻音系歌韻銳音更可能是沒有一三等對立（因而下字可以混切）的，在此暫不列舉具體證據了。

實際上 NK2028 所維護之音系資料，有數十小韻是依切韻時期其他韻書字書等資料特別修正的，因此會更不拘於《廣韻》切語，和舊有之其他《廣韻》電子資料有分析差異也是正常現象。

關於 NK2028 資料與舊有其他家資料的關係，可以參見知乎[《〈廣韻〉互聯網公開版音系資料系譜》](https://zhuanlan.zhihu.com/p/501463759)這篇文章。
